# Generated by Django 4.0.4 on 2022-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
    ]
